### ISSUE TITLE
Allow `var(--z-index--variable)`?

### ISSUE THREAD

**Issue by azu** [marcelloromanelli/stylelint-no-z-index#1]
Hi, Thanks for intersting stylelint plugin.
Is there any chance to support CSS Custom Property?

```css
/* z-index.css */
:root {
  --z-index--below: -1;
  --z-index--default: 1;
  --z-index--front: 6000001;
}

/* foo.css */
.foo {
   z-index: var(--z-index--default);
}
```
